apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent
spec:
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:alpine-jdk17
      volumeMounts:
        - name: shared-bin
          mountPath: /usr/local/bin  # Shared path for kubectl

    - name: trivy
      image: aquasec/trivy:latest
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: trivy-cache
          mountPath: /root/.cache/trivy
        - name: docker-socket
          mountPath: /var/run/docker.sock
        - name: workspace
          mountPath: /workspace
      env:
        - name: TRIVY_CACHE_DIR
          value: "/root/.cache/trivy"

    - name: docker
      image: docker:24.0.7  # Use a stable version
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
        - name: workspace
          mountPath: /workspace

    - name: kubectl
      image: bitnami/kubectl:latest  # Official kubectl image
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: shared-bin
          mountPath: /shared-bin

  volumes:
    - name: trivy-cache
      emptyDir: {}
    - name: kubectl-bin
      emptyDir: {}
    - name: shared-bin
      emptyDir: {}  # Temporary shared volume for kubectl
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket
    - name: workspace
      emptyDir: {}
