apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rollout.yaml
  - service-active.yaml
  - svc-preview.yaml
namespace: nodejs
images:
  - name: daudidrees/aks-k8s-rollouts
    newName: daudidrees/aks-k8s-rollouts
    newTag: "${BUILD_NUMBER}"