apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - app-deployment.yaml
  - service.yaml
namespace: nodejs
images:
  - name: daudidrees/aks-k8s-rollouts  # Must match deployment.yaml image
    newName: daudidrees/aks-k8s-rollouts
    newTag: "113"
