apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: nodejs
  name: jenkins-deployer
rules:
  - apiGroups: ["", "apps"]
    resources: ["deployments", "services"]
    verbs: ["get", "create", "update", "delete", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: nodejs
  name: jenkins-deployer-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: devops-tools
roleRef:
  kind: Role
  name: jenkins-deployer
  apiGroup: rbac.authorization.k8s.io
