apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-deployer
  namespace: nodejs
rules:
  - apiGroups: ["", "apps", "rbac.authorization.k8s.io"]
    resources: ["namespaces", "services", "deployments", "roles", "rolebindings"]
    verbs: ["get", "create", "update", "patch", "delete", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-deployer-binding
  namespace: nodejs
subjects:
  - kind: ServiceAccount
    name: default
    namespace: devops-tools
roleRef:
  kind: Role
  name: jenkins-deployer
  apiGroup: rbac.authorization.k8s.io

