apiVersion: v1
kind: Service
metadata:
  name: svc-preview
  namespace: nodejs
  labels:
    app: nodejs
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 1337
      nodePort: 30002
  selector:
    app: nodejs
