apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: nodejs
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 1337 # Container port
      nodePort: 30007  # Exposed NodePort (must be between 30000-32767)
